#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfff7;
constexpr uint24_t FX_DATA_BYTES = 2140;

constexpr uint24_t TreadmillUpSprite = 0x000000;
constexpr uint16_t TreadmillUpSpriteWidth  = 8;
constexpr uint16_t TreadmillUpSpriteHeight = 8;
constexpr uint8_t  TreadmillUpSpriteFrames = 8;

constexpr uint24_t TreadmillDownSprite = 0x000044;
constexpr uint16_t TreadmillDownSpriteWidth  = 8;
constexpr uint16_t TreadmillDownSpriteHeight = 8;
constexpr uint8_t  TreadmillDownSpriteFrames = 8;

constexpr uint24_t TreadmillLeftSprite = 0x000088;
constexpr uint16_t TreadmillLeftSpriteWidth  = 8;
constexpr uint16_t TreadmillLeftSpriteHeight = 8;
constexpr uint8_t  TreadmillLeftSpriteFrames = 8;

constexpr uint24_t TreadmillRightSprite = 0x0000CC;
constexpr uint16_t TreadmillRightSpriteWidth  = 8;
constexpr uint16_t TreadmillRightSpriteHeight = 8;
constexpr uint8_t  TreadmillRightSpriteFrames = 8;

constexpr uint24_t SandtrapSprite = 0x000110;
constexpr uint16_t SandtrapSpriteWidth  = 8;
constexpr uint16_t SandtrapSpriteHeight = 8;

constexpr uint24_t HoleNoFlagSprite = 0x00011C;
constexpr uint16_t HoleNoFlagSpriteWidth  = 8;
constexpr uint16_t HoleNoFlagSpriteHeight = 8;
constexpr uint8_t  HoleNoFlagSpriteFrames = 4;

constexpr uint24_t HoleWithFlagSprite = 0x000160;
constexpr uint16_t HoleWithFlagSpriteWidth  = 8;
constexpr uint16_t HoleWithFlagSpriteHeight = 16;
constexpr uint8_t  HoleWithFlagSpriteFrames = 4;

constexpr uint24_t Maps = 0x0001E4;
